default_chroma_path: "./chroma"
default_collection_name: "my_collection"
default_chunk_size: 300
default_chunk_overlap: 150
num_result_entries_from_db: 3
database_embedding: "sentence-transformers/all-MiniLM-L6-v2"
query_embedding: "sentence-transformers/all-MiniLM-L6-v2"